apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- spring-mvc-demo.yaml
- session.yml
- session-scaler.yaml

patches:
- path: image-version/spring-mvc-demo.yaml
